schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0"
    hash = "sha256-APnPAcmItvtJ5Zsy863lzR2TjEBF9Y66TY1e4M1ap98="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.2.1"
    hash = "sha256-Z1dlsUTjF8SJZCknYKt7ufJz8NPGg9P9+W17DQn+LO0="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.0"
    hash = "sha256-JaGYNQwDxFCsLwzYVoJY4RUpP4dtiRlV14t2dVAg4oQ="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.0"
    hash = "sha256-TQ0AvXZfuT3PDnb4p/h5zmyT8m9VPcwxlXMJuVD6ltE="
  [mod."github.com/adrg/xdg"]
    version = "v0.4.0"
    hash = "sha256-zGjkdUQmrVqD6rMO9oDY+TeJCpuqnHyvkPCaXDlac/U="
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.5.0"
    hash = "sha256-eYjXjerKbWc3IZACr771c3y3kFQmhmeahU57N8Nfbtw="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr"]
    version = "v1.4.10"
    hash = "sha256-QZn1eltqxkZYvf7g/GQv6HftH+OuKJTVjIjyyHZw9jI="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.6.4"
    hash = "sha256-R7YqukuP0RQW+F5kwgWzjxyvlGuJ0VNAUk2dAMXI4bs="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.17.2"
    hash = "sha256-FPvR3VeoI+VdMkrkT+TUSgpnlMm85gUqlFfq8/HMo9c="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chzyer/readline"]
    version = "v1.5.1"
    hash = "sha256-6wKd6/JZ9/O7FwSyNKE3KOt8fVPZEunqbTHQUxlOUNc="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.1"
    hash = "sha256-Wr9ovXhGi71+n37EnrpIj2o9goyaQHtY4Vvurv6IVlY="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.8.1"
    hash = "sha256-Xm4I+Qrpwn21QsWcUMden00zWapbloa6K1yJ83tTOVE="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fatih/color"]
    version = "v1.14.1"
    hash = "sha256-cCjkicVuBK19gkNKHU4BhKNKETfGKPx72Rus473HbcY="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.4.0"
    hash = "sha256-LwOrfDN5fx/R2lgaD90RIu2NxcJDpyqYEURLc9Kgxgw="
  [mod."github.com/go-chi/chi"]
    version = "v4.1.2+incompatible"
    hash = "sha256-KpvSwEqRBeUBZae9r7J3sMCpJMqyaKtEn1KKfKTa0O0="
  [mod."github.com/go-kit/kit"]
    version = "v0.12.0"
    hash = "sha256-5RkXo6s0oye8etgD5qy+AvkkkNsQ6jc0kWJj6flA4GM="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.7.0"
    hash = "sha256-xcCINvN+wEiLLmp9ltfLbDEs+/TidoBCQLODw3lMyzE="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20210107165309-348f09dbbbc0"
    hash = "sha256-jgza4peLzeJlwmMh/c1gNkmtwA9YtSdGaBzBUDXhIZo="
  [mod."github.com/go-yaml/yaml"]
    version = "v2.1.0+incompatible"
    hash = "sha256-GnvviYeQD24hLkBKR+1ye9Cng+Ohy0hjvabPl+5z6kw="
  [mod."github.com/golang/glog"]
    version = "v1.0.0"
    hash = "sha256-bglITqRgzi52zc6FoYYnfCvrjFWV4RVOacPCnbEBom4="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.13.0"
    hash = "sha256-J1K+7oGrGrZanRzomfqhlHN681wElApLa9RCyV5lR2Y="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20230222194610-99052d3372e7"
    hash = "sha256-VDPZx4D4AQw63TEG1c1Wq36o9JLm1FWLr+SO1WL1Vng="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/huandu/xstrings"]
    version = "v1.4.0"
    hash = "sha256-lw0qFsUNW6ZPXNwawpUSfJQjZ+/PKMLkC/yW64t1yng="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.14.0"
    hash = "sha256-99prYm457c62a5p5ZnB3FgAsoPBK1TFrheIHdZhLf7k="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.3.2"
    hash = "sha256-/5UWuc3rR/aBwcNZ4gDiMoYIrkWs5UQkrfQj2//vmIU="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20221227161230-091c0ba34f0a"
    hash = "sha256-rBtUw15WPPDp2eulHXH5e2zCIed1OPFYwlCpgDOnGRM="
  [mod."github.com/jackc/pgtype"]
    version = "v1.14.0"
    hash = "sha256-vGfWF6+NzFWS6XhFXEjrxxG44/kSSj1fB5j9OuNQlQs="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.18.0"
    hash = "sha256-fKchqDzC1CrMzKh3tTgWud51QGv1KM26s5L2YMnrs7M="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/kardianos/osext"]
    version = "v0.0.0-20190222173326-2bc1f35cddc0"
    hash = "sha256-uTDfg87dfqCz32K6Sc1Glj/8/oJXudUd6JW4XHdeed8="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.15"
    hash = "sha256-fMVJFz/P37vjZAf82nHjaItaB3gesOa+xV7uBuo3kmg="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.4"
    hash = "sha256-EjWkW6py3nYOut+YY9waTI2OegIFQWuJRS1hZ+F+obU="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.17"
    hash = "sha256-c1u9eiMF9wLXgGvPTB5DH6S8uuCPqWZJTa6tCGuB3Ek="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez"]
    version = "v1.1.0"
    hash = "sha256-RPI/IoE/HFrgjRQQZRx6x7+rhnyoHJ+B7AOyBQl4Y6w="
  [mod."github.com/micromdm/scep/v2"]
    version = "v2.1.0"
    hash = "sha256-vs0CBvUVXRh6n+XI7GlvdijNC9/Vec0LpywCCEivo0g="
  [mod."github.com/miekg/dns"]
    version = "v1.1.50"
    hash = "sha256-mtf3QAk46pCA0a1K+oH6a7oqsY6LR6Qr8HD4qnDqe+s="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.8.3"
    hash = "sha256-AF1jsVXns7/zxTkUcNSLJ4VBVZ+rT0NENKmk1p/qSgg="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.40.0"
    hash = "sha256-ykOktYSNsCYKR4Ru7UWoebIgzMqJjLG2jrbmO7NBv08="
  [mod."github.com/prometheus/procfs"]
    version = "v0.9.0"
    hash = "sha256-imZN+1HRpMvgmrot2V+AK5ueYLmsp49vZfHtx2N6Wek="
  [mod."github.com/quic-go/qpack"]
    version = "v0.4.0"
    hash = "sha256-QWIumzmHD94DlNp9G3AQf9QCtF+Kv0pShT1+FH7/I/c="
  [mod."github.com/quic-go/qtls-go1-19"]
    version = "v0.2.1"
    hash = "sha256-5Bg+5u1+9nPGeX3F+KXb0ASeuRbpTYQWSdLOHx9hkZE="
  [mod."github.com/quic-go/qtls-go1-20"]
    version = "v0.1.1"
    hash = "sha256-/WMP+Kl5w2LrmUYjj+HUq6xv3ihPgOcU+IWHSGkDNjc="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.33.0"
    hash = "sha256-wat+dGCALgzLQT1+Wi/gBsERQ9OJocUdxjnmHCTyt5A="
  [mod."github.com/rs/xid"]
    version = "v1.4.0"
    hash = "sha256-X7WH1cxWBof4m8ZWCnP0VYQdwzBti2eoa/sqm3BmLcg="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sevlyar/go-daemon"]
    version = "v0.1.6"
    hash = "sha256-CyCp/d/VKPbb75NyIuRrCKWg/Xl2S6MejBKEFw6yWvQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.3.1"
    hash = "sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/slackhq/nebula"]
    version = "v1.6.1"
    hash = "sha256-wN7zB/iB1mjfG5KyS3yvxaYu12VgkNzV7z9i2Yaod7Q="
  [mod."github.com/smallstep/certificates"]
    version = "v0.23.2"
    hash = "sha256-TsNxhq85cIeOQg132SOggFjd9+2ZnSdb2jDmbu4g9B4="
  [mod."github.com/smallstep/nosql"]
    version = "v0.5.0"
    hash = "sha256-NK1vuxk+C0lnXzMIaolCn8SnGTghjgY/IXPHL3Hah9w="
  [mod."github.com/smallstep/truststore"]
    version = "v0.12.1"
    hash = "sha256-Kboc+343ZeGFeCnYxeH2Wd04M2Gsk9CNMAMnA0keRxk="
  [mod."github.com/spf13/cast"]
    version = "v1.5.0"
    hash = "sha256-Pdp+wC5FWqyJKzyYHb7JCcV9BoJk/sxQw6nLyuLJvuQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.6.1"
    hash = "sha256-80B5HcYdFisz6QLYkTyka7f9Dr6AfcVyPwp3QChoXwU="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.2.1"
    hash = "sha256-KvFlKlkgfLKt61JG6YsamiSvdYAKxHONJPEWOqrPIhE="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.1"
    hash = "sha256-3e0vOJLgCMAan+GfaGN8RGZdarh5iCavM6flf6YMNPk="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20230124224810-c6dc1f4049b2"
    hash = "sha256-0wDs4lHMgM+NTf82yBx7uNZYiyOsB5FrjbFGLjg4Ygo="
  [mod."github.com/urfave/cli"]
    version = "v1.22.12"
    hash = "sha256-FTdBlhQvyDhgrDcSJDxgSLS/cBSP8B1BC/AxGA9Lyss="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.4"
    hash = "sha256-4he5sGi0uj1LogdqvgpvN8b7p6qlKMGuWXRFzh+FK8s="
  [mod."github.com/yuin/goldmark-highlighting/v2"]
    version = "v2.0.0-20220924101305-151362477c87"
    hash = "sha256-3ADuEiUgqK7LiaakT9DfKh795GNfFKBq/dIu5Tez01o="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.7"
    hash = "sha256-poZk8tPLDWwW95oCOkTJcQtEvOJTD9UXAZ2TqGJutwk="
  [mod."go.mozilla.org/pkcs7"]
    version = "v0.0.0-20210826202110-33d05740a352"
    hash = "sha256-x5OuHrnMWNfcLZCyQ6zaGm+ah8DMli2CCQg5z6qWgb8="
  [mod."go.step.sm/cli-utils"]
    version = "v0.7.5"
    hash = "sha256-ghW15CjqPsMYm03E8iqVVv6+lRjJumWoSRhxxf6VCzE="
  [mod."go.step.sm/crypto"]
    version = "v0.25.0"
    hash = "sha256-UyilZcfRzdFACRU7GsLy9GfXruQQIvGVXoaAnsAf2Ww="
  [mod."go.step.sm/linkedca"]
    version = "v0.19.0"
    hash = "sha256-2P+JMeECHxoBzFL6LUnSg6IhtuMDDSp5qTpu9TL9uKI="
  [mod."go.uber.org/atomic"]
    version = "v1.10.0"
    hash = "sha256-E6UEDc1eh/cLUFd+J86cDesQ0B8wEv/DdaAVKb+x2t8="
  [mod."go.uber.org/goleak"]
    version = "v1.2.0"
    hash = "sha256-lwg6vzOTMo3pZTwiniWiRdCUFuKbxBQnRlM59/zh+NI="
  [mod."go.uber.org/multierr"]
    version = "v1.9.0"
    hash = "sha256-tlDRooh/V4HDhZohsUrxot/Y6uVInVBtRWCZbj/tPds="
  [mod."go.uber.org/zap"]
    version = "v1.24.0"
    hash = "sha256-yLzjFbMWnc5b033gcPLGP0KY1xWPJ3sjnUG/RndmC3o="
  [mod."golang.org/x/crypto"]
    version = "v0.6.0"
    hash = "sha256-rtJfWOcpCk+DUskDsOZBt9BU/pHjHJ60LkF4VOKCAI8="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20230223210539-50820d90acfd"
    hash = "sha256-z/EGI+tv5SGd7AKvfP56a5lmb3eF2UkcReorK6gydCg="
  [mod."golang.org/x/mod"]
    version = "v0.8.0"
    hash = "sha256-cgtmxQA937+MdXUiPrVeDvRoqhxD4hvIbtXAjK2SM8U="
  [mod."golang.org/x/net"]
    version = "v0.7.0"
    hash = "sha256-LgZYZRwtMqm+soNh+esxDSeRuIDxRGb9OEfYaFJHCDI="
  [mod."golang.org/x/oauth2"]
    version = "v0.5.0"
    hash = "sha256-+ns+lPELOJdb1YpIxQRBVQeSEsn0VhnKPnHg5Q0NOH4="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.5.0"
    hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="
  [mod."golang.org/x/term"]
    version = "v0.5.0"
    hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="
  [mod."golang.org/x/text"]
    version = "v0.7.0"
    hash = "sha256-ydgUqX+t5Qke16C6d3FP/06U/N1n+rUKpLRFj4KXjwk="
  [mod."golang.org/x/tools"]
    version = "v0.6.0"
    hash = "sha256-J0q+C3WDTK9yyHX90FV6qr6n9H07YglYg1p4H3MqyH4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230223222841-637eb2293923"
    hash = "sha256-eEBzbHhUJwkfigrtus0l2mFHbLLqBcfv5j+T+Yh4+Ss="
  [mod."google.golang.org/grpc"]
    version = "v1.53.0"
    hash = "sha256-LkB13k1JaQ7e4nGpCoEA9q4T8oIV0KvkFIDZmHhDr08="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.6.0"
    hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.0"
    hash = "sha256-sySpZjk+EXYSv4cqtRiyVWOQ68W/SlrE/uyI4o/5CGY="
