# localias config file syntax
#
# 	alias: port
#
# for example,
#
#   https://secure.test: 9000
#   http://insecure.test: 9001
#   insecure2.test: 9002
#   bareTLD: 9003
#
bare: "9003"
bare.local: "9002"
http://insecure.local: "9001"
https://secure.local: "9000"
invalid://failure: "9004"
valid.duplicate: "9000"
