# localias config file syntax
#
# 	alias: port
#
# for example,
#
#   bareTLD: 9003 # serves over https and http
#   implicitly_secure.test: 9002 # serves over https and http
#   https://explicit_secure.test: 9000 # serves over https and http
#   http://explicit_insecure.test: 9001 # serves over http only
#
bare: 9003
bare.test: 9002
invalid://failure: 9004
valid.duplicate: 9000
http://insecure.test: 9001
https://secure.test: 9000
